# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev-minimal-example',
                'doc_host': 'https://jimmiemunyi.github.io',
                'git_url': 'https://github.com/jimmiemunyi/nbdev-minimal-example',
                'lib_path': 'nbdev_minimal_example'},
  'syms': {'nbdev_minimal_example.core': {'nbdev_minimal_example.core.foo': ('core.html#foo', 'nbdev_minimal_example/core.py')}}}